/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "lv_test_init.h"
#include "../lvgl.h"
#include "lv_test_indev.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_arc_creation_successfull(void);
extern void test_arc_should_truncate_to_max_range_when_new_value_exceeds_it(void);
extern void test_arc_should_truncate_to_min_range_when_new_value_is_inferior(void);
extern void test_arc_should_update_value_after_updating_range(void);
extern void test_arc_should_update_angles_when_changing_to_symmetrical_mode(void);
extern void test_arc_should_update_angles_when_changing_to_symmetrical_mode_value_more_than_middle_range(void);
extern void test_arc_angles_when_reversed(void);
extern void test_arc_click_area_with_adv_hittest(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Suite Setup=====*/
void suiteSetUp(void)
{
lv_test_init();
}

/*=======Suite Teardown=====*/
int suiteTearDown(int num_failures)
{
lv_test_deinit();return num_failures;
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  suiteSetUp();
  UnityBegin("./src/test_cases/test_arc.c");
  run_test(test_arc_creation_successfull, "test_arc_creation_successfull", 10);
  run_test(test_arc_should_truncate_to_max_range_when_new_value_exceeds_it, "test_arc_should_truncate_to_max_range_when_new_value_exceeds_it", 11);
  run_test(test_arc_should_truncate_to_min_range_when_new_value_is_inferior, "test_arc_should_truncate_to_min_range_when_new_value_is_inferior", 12);
  run_test(test_arc_should_update_value_after_updating_range, "test_arc_should_update_value_after_updating_range", 13);
  run_test(test_arc_should_update_angles_when_changing_to_symmetrical_mode, "test_arc_should_update_angles_when_changing_to_symmetrical_mode", 14);
  run_test(test_arc_should_update_angles_when_changing_to_symmetrical_mode_value_more_than_middle_range, "test_arc_should_update_angles_when_changing_to_symmetrical_mode_value_more_than_middle_range", 15);
  run_test(test_arc_angles_when_reversed, "test_arc_angles_when_reversed", 16);
  run_test(test_arc_click_area_with_adv_hittest, "test_arc_click_area_with_adv_hittest", 126);

  return suiteTearDown(UnityEnd());
}
