/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "lv_test_init.h"
#include "../lvgl.h"
#include "lv_test_indev.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_dropdown_create_delete(void);
extern void test_dropdown_set_options(void);
extern void test_dropdown_select(void);
extern void test_dropdown_click(void);
extern void test_dropdown_keypad(void);
extern void test_dropdown_encoder(void);
extern void test_dropdown_render_1(void);
extern void test_dropdown_render_2(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Suite Setup=====*/
void suiteSetUp(void)
{
lv_test_init();
}

/*=======Suite Teardown=====*/
int suiteTearDown(int num_failures)
{
lv_test_deinit();return num_failures;
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  suiteSetUp();
  UnityBegin("./src/test_cases/test_dropdown.c");
  run_test(test_dropdown_create_delete, "test_dropdown_create_delete", 7);
  run_test(test_dropdown_set_options, "test_dropdown_set_options", 8);
  run_test(test_dropdown_select, "test_dropdown_select", 9);
  run_test(test_dropdown_click, "test_dropdown_click", 10);
  run_test(test_dropdown_keypad, "test_dropdown_keypad", 11);
  run_test(test_dropdown_encoder, "test_dropdown_encoder", 12);
  run_test(test_dropdown_render_1, "test_dropdown_render_1", 13);
  run_test(test_dropdown_render_2, "test_dropdown_render_2", 14);

  return suiteTearDown(UnityEnd());
}
