/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "lv_test_init.h"
#include "../lvgl.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_txt_should_identify_valid_start_of_command(void);
extern void test_txt_should_identify_invalid_start_of_command(void);
extern void test_txt_should_identify_scaped_command_in_parameter(void);
extern void test_txt_should_skip_color_parameter_in_parameter(void);
extern void test_txt_should_reset_state_when_receiving_color_cmd_while_processing_commands(void);
extern void test_txt_should_identify_space_after_parameter(void);
extern void test_txt_should_insert_string_into_another(void);
extern void test_txt_should_handle_null_pointers_when_inserting(void);
extern void test_txt_cut_should_handle_null_pointer_to_txt(void);
extern void test_txt_cut_happy_path(void);
extern void test_txt_cut_should_handle_len_longer_than_string_length(void);
extern void test_txt_get_encoded_next_should_decode_valid_ascii(void);
extern void test_txt_get_encoded_next_detect_valid_2_byte_input(void);
extern void test_txt_get_encoded_next_detect_invalid_2_byte_input(void);
extern void test_txt_get_encoded_next_detect_valid_3_byte_input(void);
extern void test_txt_get_encoded_next_detect_invalid_3_byte_input(void);
extern void test_txt_get_encoded_next_detect_valid_4_byte_input(void);
extern void test_txt_get_encoded_next_detect_invalid_4_byte_input(void);
extern void test_txt_next_line_should_handle_empty_string(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Suite Setup=====*/
void suiteSetUp(void)
{
lv_test_init();
}

/*=======Suite Teardown=====*/
int suiteTearDown(int num_failures)
{
lv_test_deinit();return num_failures;
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  suiteSetUp();
  UnityBegin("./src/test_cases/test_txt.c");
  run_test(test_txt_should_identify_valid_start_of_command, "test_txt_should_identify_valid_start_of_command", 8);
  run_test(test_txt_should_identify_invalid_start_of_command, "test_txt_should_identify_invalid_start_of_command", 19);
  run_test(test_txt_should_identify_scaped_command_in_parameter, "test_txt_should_identify_scaped_command_in_parameter", 30);
  run_test(test_txt_should_skip_color_parameter_in_parameter, "test_txt_should_skip_color_parameter_in_parameter", 41);
  run_test(test_txt_should_reset_state_when_receiving_color_cmd_while_processing_commands, "test_txt_should_reset_state_when_receiving_color_cmd_while_processing_commands", 52);
  run_test(test_txt_should_identify_space_after_parameter, "test_txt_should_identify_space_after_parameter", 63);
  run_test(test_txt_should_insert_string_into_another, "test_txt_should_insert_string_into_another", 74);
  run_test(test_txt_should_handle_null_pointers_when_inserting, "test_txt_should_handle_null_pointers_when_inserting", 88);
  run_test(test_txt_cut_should_handle_null_pointer_to_txt, "test_txt_cut_should_handle_null_pointer_to_txt", 101);
  run_test(test_txt_cut_happy_path, "test_txt_cut_happy_path", 106);
  run_test(test_txt_cut_should_handle_len_longer_than_string_length, "test_txt_cut_should_handle_len_longer_than_string_length", 115);
  run_test(test_txt_get_encoded_next_should_decode_valid_ascii, "test_txt_get_encoded_next_should_decode_valid_ascii", 124);
  run_test(test_txt_get_encoded_next_detect_valid_2_byte_input, "test_txt_get_encoded_next_detect_valid_2_byte_input", 134);
  run_test(test_txt_get_encoded_next_detect_invalid_2_byte_input, "test_txt_get_encoded_next_detect_invalid_2_byte_input", 144);
  run_test(test_txt_get_encoded_next_detect_valid_3_byte_input, "test_txt_get_encoded_next_detect_valid_3_byte_input", 154);
  run_test(test_txt_get_encoded_next_detect_invalid_3_byte_input, "test_txt_get_encoded_next_detect_invalid_3_byte_input", 164);
  run_test(test_txt_get_encoded_next_detect_valid_4_byte_input, "test_txt_get_encoded_next_detect_valid_4_byte_input", 174);
  run_test(test_txt_get_encoded_next_detect_invalid_4_byte_input, "test_txt_get_encoded_next_detect_invalid_4_byte_input", 184);
  run_test(test_txt_next_line_should_handle_empty_string, "test_txt_next_line_should_handle_empty_string", 195);

  return suiteTearDown(UnityEnd());
}
