/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "lv_test_init.h"
#include "../lvgl.h"
#include "lv_test_indev.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_checkbox_creation_successfull(void);
extern void test_checkbox_should_call_event_handler_on_click_when_enabled(void);
extern void test_checkbox_should_have_default_text_when_created(void);
extern void test_checkbox_should_return_dinamically_allocated_text(void);
extern void test_checkbox_should_allocate_memory_for_static_text(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Suite Setup=====*/
void suiteSetUp(void)
{
lv_test_init();
}

/*=======Suite Teardown=====*/
int suiteTearDown(int num_failures)
{
lv_test_deinit();return num_failures;
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  suiteSetUp();
  UnityBegin("./src/test_cases/test_checkbox.c");
  run_test(test_checkbox_creation_successfull, "test_checkbox_creation_successfull", 8);
  run_test(test_checkbox_should_call_event_handler_on_click_when_enabled, "test_checkbox_should_call_event_handler_on_click_when_enabled", 9);
  run_test(test_checkbox_should_have_default_text_when_created, "test_checkbox_should_have_default_text_when_created", 10);
  run_test(test_checkbox_should_return_dinamically_allocated_text, "test_checkbox_should_return_dinamically_allocated_text", 11);
  run_test(test_checkbox_should_allocate_memory_for_static_text, "test_checkbox_should_allocate_memory_for_static_text", 12);

  return suiteTearDown(UnityEnd());
}
